### ISSUE TITLE
1 product with multiple colors

### ISSUE THREAD

**Issue by Mark-Hoog** [lovata/oc-shopaholic-plugin#25]
Hello Good folk,

At the moment I am researching which plugin I want to use for a customer that needs simple product buying options. I am wondering if it is possible to create one product that has several different colors (or sizes). 

Example:
Samsung Galaxy S9
  -  Gold
  -  Black
  -  Rose

With Kind Regards,

**Comment by kharanenka** [comment]
Hi!
The [Shopaholic](https://octobercms.com/plugin/lovata-shopaholic) plugin is great for this task.
Samsung Galaxy S9 is product, Samsung Galaxy S9 Gold is offer of the product.
You can use the [Properties for Shopaholic](https://octobercms.com/plugin/lovata-propertiesshopaholic) plugin to quickly display the properties of products (size, battery) and offers (color, storage and memory). You can use the [Filter for Shopaholic](https://octobercms.com/plugin/lovata-filtershopaholic) plugin to quickly add filtering to the project by the properties of the products and offers.

Thank you for your interest in our plugins!

**Comment by lautsevich** [comment]
Hi, Mark! We can give you a personal promo code for buying Properties and Filter for Shopaholic for a minimum price $5 for a less expensive testing! Just email us to info@lovata.com.

**Comment by lautsevich** [comment]
Yep, we have plans to create a demo site in the near future.

**Comment by realrandal** [comment]
Guys, thanks for great product. I'm using properties plugin already. 

Although full feature demo theme would be very helpful here. 

Will you include ajax cart and one page ajax checkout (without steps)? 
Is it possible in shopaholic?

**Comment by kharanenka** [comment]
Hi!
You can use the [Orders for Shopaholic](https://octobercms.com/plugin/lovata-ordersshopaholic) plugin for this task.
The [Cart](https://github.com/lovata/oc-shopaholic-plugin/wiki/Cart) component is great for ajax cart.
You can use the the [MakeOrder](https://github.com/lovata/oc-shopaholic-plugin/wiki/MakeOrder) component for creating order with ajax. You can get number of order in ajax response and display it in message for user.

**Comment by realrandal** [comment]
Yes, I digging docs. Cannot find any example of it working. Did you have any online?
I just asked. So... it is possible to have all info on one page with MakeOrder component? 
Can I mix it with addresses, shipping, payment, totals etc?

I see, your components are build very developer way. Not much properties in component settings but all  via code. This is done like that because it's not finished or rather for bigger flexibility of custom views?

**Comment by kharanenka** [comment]
Please write in more detail the logic of the basket and the order that you need to develop. We will add a step to the quick start guide, to solve this task.

Our components are designed for easy extensibility. We want developers to use plugins, they could make custom logic, without freezing plugins.

We want to improve plugins and add methods that developers will need.

**Comment by realrandal** [comment]
[Here](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=9132&filter_download_id=26&page=5) you have what I use already. 

As long I will not be able to get this type of simplicity, there will be no big reason to switch from opencart. I can accept lose of tons of extensions and integrations. But basics as performance and quick checkout process must be perfected. This is minimum.

It seems [HareShop](https://octobercms.com/theme/hareshop-simple) plugin has it already (look at screenshots). But I choose shopaholic as your job seems much better written, have more features and better thought as a whole.

**Comment by kharanenka** [comment]
Hi!
We will add today and tomorrow several steps in a quick start guide. They will describe how to develop different versions of the cart and checkout.

**Comment by realrandal** [comment]
Thanks for reply. 
Few more questions:
1. When demo theme will be available? 
2. Why not make one page checkout as default?
3. What if I want to develop whole shop on Vue.js (SPA)? Will plugin allow me to do this or I need to create API output for everything by my own plugins?
4. Why you decide to not use Responsiv.Pay (invoices and payment) and Rainlab.User but rather omnipay and Buddies? I know Buddies have custom profiles, but also this functionality could have been added to Rainlab.User instead of making separate plug?

I try to understand your moves because I'm learning here everything and want to be sure we hit the mark.

**Comment by kharanenka** [comment]
1. We plan to make a  demo site in the near future. We want to create an open repository with a demo site so that developers can download a demo site and see the page code.
2. The plugin allows you to make an checkout page without steps now. We will add a step to a quick start guide.
3. Plugins do not support routes for the API. But you can easily add routes to the API in your application, using collection and items objects. Now you use collection and items objects in templates, but you can easily use it in code of your component. This is good functionality for the new plugin in marketplace!))
4. We are building a large ecosystem of plugins for OcotberCMS. We develop the plugins so that when you install them, you do not get a lot of extra functionality. Therefore, integration with Responsiv.Pay plugin should be designed as a separate plugin.
We are considering the possibility of integration with Rainlab.User in the near future.
