### ISSUE TITLE
Plugin "Omnipay for Shopaholic" assume OC composer installation

### ISSUE THREAD

**Issue by alvaro-canepa** [lovata/oc-shopaholic-plugin#47]
If OC was installed from wizard `install.php`, Is not possible to add required **Omnipay** package to `composer.json`. And then, when create a new payment method have this error.

![image](https://user-images.githubusercontent.com/5142298/36061623-2d5be126-0e3b-11e8-8aaf-d72c00056b3f.png)

**Comment by kharanenka** [comment]
We can not add installed Omnipay packages to the plug-in code, because this leads in some situations to the conflict of packages and errors of the entire application. The safest way is to install packages at the root of the project. If you do not have a composer.json file in the project root, you can create it in the plugin folder. But we do not recommend this method. When you update OctoberCMS, errors may occur.
